repos:
  - repo: local
    hooks:
      # Run the formatter.
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: uvx ruff format
        language: system
        types_or: [python, pyi]
        args: [--config=pyproject.toml]
      # Run the linter.
      - id: ruff-lint
        name: ruff-lint
        description: "Run 'ruff' for extremely fast Python linting"
        entry: uvx ruff check --fix
        language: system
        types_or: [python, pyi]
        args: [--config=pyproject.toml]
